name: mlpca
dependencies:  # Version numbers should all be the most recent releases, for the most part. I specify the major/minor version numbers to help ensure replicability.
 - python=3.7
 - numpy=1.16.*
 - scikit-learn=0.21.*
 - pytest=5.*
